from __future__ import annotations

START_FIXED = 0x10
START_VARIABLE = 0x68
END_FRAME = 0x16

CONTROL_PRM = 0x40
CONTROL_FCB = 0x20
CONTROL_FCV = 0x10

MASTER_RESET_REMOTE_LINK = 0
MASTER_SEND_USER_DATA = 3
MASTER_REQUEST_LINK_STATUS = 9
MASTER_REQUEST_CLASS_2_DATA = 11

SLAVE_ACK = 0
SLAVE_NACK = 1
SLAVE_USER_DATA = 8
SLAVE_NO_DATA = 9
SLAVE_STATUS = 11

CAUSE_INITIALIZED = 4
CAUSE_REQUEST = 5
CAUSE_ACTIVATION = 6
CAUSE_ACTIVATION_CONFIRM = 7
CAUSE_ACTIVATION_TERMINATION = 10
CAUSE_DATA_NOT_AVAILABLE = 13
CAUSE_ASDU_NOT_AVAILABLE = 14
CAUSE_RECORD_UNKNOWN = 15
CAUSE_ADDRESS_UNKNOWN = 16
CAUSE_OBJECT_NOT_AVAILABLE = 17
CAUSE_PERIOD_NOT_AVAILABLE = 18

TYPE_INTEGRATED_TOTALS = 8
TYPE_INCREMENTAL_TOTALS = 11
TYPE_MANUFACTURER_IDENTIFICATION = 71
TYPE_CURRENT_TIME = 72
TYPE_READ_MANUFACTURER_IDENTIFICATION = 100
TYPE_READ_CURRENT_TIME = 103
TYPE_READ_INTEGRATED_TOTALS = 122
TYPE_READ_INCREMENTAL_TOTALS = 123
TYPE_READ_INSTANT_VALUES = 162
TYPE_INSTANT_VALUES = 163
TYPE_LOGIN = 183
TYPE_LOGOUT = 187

OBJECT_ACTIVE_IMPORT = 1
OBJECT_ACTIVE_EXPORT = 2
OBJECT_REACTIVE_IMPORT_Q1 = 3
OBJECT_REACTIVE_IMPORT_Q2 = 4
OBJECT_REACTIVE_EXPORT_Q3 = 5
OBJECT_REACTIVE_EXPORT_Q4 = 6
OBJECT_TOTAL_TARIFF = 20
OBJECT_TARIFF_1 = 21
OBJECT_TARIFF_2 = 22
OBJECT_TARIFF_3 = 23
OBJECT_TARIFF_4 = 24
OBJECT_INSTANT_ENERGY_BLOCK = 192
OBJECT_INSTANT_POWER_BLOCK = 193
OBJECT_INSTANT_VOLTAGE_CURRENT_BLOCK = 194

DEFAULT_TCP_HOST = "0.0.0.0"
DEFAULT_TCP_PORT = 4001
DEFAULT_SERIAL_TIMEOUT = 1.0
DEFAULT_BAUDRATE = 9600
DEFAULT_PARITY = "E"
DEFAULT_BYTESIZE = 8
DEFAULT_STOPBITS = 1
DEFAULT_TIME_ACCELERATION = 1.0

SUPPORTED_TIME_ACCELERATIONS = [1, 10, 60, 100, 1000]
ENERGY_SCALE = 1000
